# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            aboza.dev
tagline:          ''
description:      ''
url:              abozadev.me
baseurl:

author:
  name:           'August Boza'
  url:            https://twitter.com/abozadev

#paginate:         5

github:
  repo:           https://github.com/abozadev/abozadev.github.io
